env:
  seed: 1
  scene_id: 0  # 0 warehouse, 1 garage, 3 natureforest
  num_envs: 100
  num_threads: 10
  render: no
  sim_dt: 0.02
  max_time: 5.0

quadrotor:
  mass: 0.73
  arm_length: 0.17
  rotor_drag_coeff: 0.016 
  inertia: [0.007, 0.007, 0.012]
  camera: no

rl:
  Q_pos: [-0.01, -0.01, -0.01]
  Q_ori: [-0.01, -0.01, -0.01]
  Q_lin_vel: [-0.001, -0.001, -0.001]
  Q_act: [-0.0001, -0.0001, -0.0001, -0.0001]