name: CPP_CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: realyunlong/flightmare_dep
    
    steps:
    - uses: actions/checkout@v2

    - name: cmake
      run: pwd && cd flightlib/build && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_TEST=ON -DEIGEN_FROM_SYSTEM=OFF ..
    - name: make
      run: cd flightlib/build && make -j${nprog}
    - name: test
      env: 
        FLIGHTMARE_DIR: /github/home/flightmare/flightmare
      run: cd flightlib/build && ./test_lib
